spring:
  application:
    name: ContactList
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost/contact?serverTimezone=Europe/Moscow&useSSL=false
    username: root
    password: root